# Generated by Django 5.0.2 on 2024-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
